### ISSUE TITLE
- Error en validacion de input

### ISSUE THREAD

**Issue by Yenny-1301** [Villanueva-Flavio/TP2-Algo2-Calvo-1C2023#11]
Cuando un usuario desea mover una ficha con los controles e ingresa un valor que no esta dentro del rango se imprimen 3 mensajes de error y se crea un loop de ingreso de coordenadas

**Comment by Villanueva-Flavio** [comment]
No se encontró el bug en la rama Pozzard / Gero -> Se mergeara a main para trasladar esa version
